## The two functions are used to create a special "matrix" object and cache 
## the inverse of a square matrix, which is assumed to be always invertible.

## If the inverse of the matrix has already been computed, the functions return 
## the inverse of the non modified matrix from the cache. 
## Otherwise, the functions compute the inverse and store it in the cache.


## The function "makeCacheMatrix" has as argument an invertible matrix 
## and returns a list of four elements.
## It is constituted of four fuctions:
## - the function "set" assigns the values of the matrix;
## - the function "get" returns the matrix;
## - the function "setInverse" assigns the inverse matrix in the object "inv";
## - the function "getInverse" returns the inverse matrix.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    
    get <- function() x
    
    setInverse <- function(inverse) inv <<- inverse
    
    getInverse <- function() inv
    
    list(set = set, get = get,
         setInverse = setInverse, 
         getInverse = getInverse)
}


## The function "cacheSolve" has as argument the list generated by the previous 
## function. If the inverse of the non modified matrix has been already computed, 
## the function returns it from the cache without computing it again and prints 
## the message: "Getting cached data". Otherwise, the function computes and
## return the inverse of the matrix preceded by the message: "Computing inverse of matrix".     

cacheSolve <- function(list, ...) {
    inv <- list$getInverse()
    
    if(!is.null(inv)){
        message("Getting cached data")
        return(inv)
    }
    
    message("Computing inverse of matrix")
    values <- list$get()
    inv <- solve(values, ...)
    list$setInverse(inv)
    
    inv
}